name: Bump

on:
  push:
    branches: [main]

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Caches
        uses: actions/cache@v2
        id: yarn-node-module-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}

      - name: Node14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install
        if: steps.yarn-node-module-cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Setup git config
        run: |
          git config --local user.email "kirby@bot.com"
          git config --local user.name "CI Bot"

      - run: yarn bump:patch
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true
