name: Tests

on: [push]

jobs:
  perf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Caches
        uses: actions/cache@v2
        id: yarn-build-cache
        with:
          path: |
            .next/cache
            node_modules
            ~/.cache/Cypress
            build
          key: ${{ runner.os }}-node_modules-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-build-

      - name: Node14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install
        run: npm install && npm install -g @lhci/cli@0.7.x

      - name: Lhci
        run: lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Caches
        uses: actions/cache@v2
        id: yarn-build-cache
        with:
          path: |
            .next/cache
            node_modules
            ~/.cache/Cypress
            build
          key: ${{ runner.os }}-node_modules-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-build-

      - name: Node12
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install
        run: yarn install

      - name: Jest
        run: yarn coverage

      - name: Store Artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Caches
        uses: actions/cache@v2
        id: yarn-build-cache
        with:
          path: |
            .next/cache
            node_modules
            ~/.cache/Cypress
            build
          key: ${{ runner.os }}-node_modules-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-build-

      - name: Node14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install
        run: yarn install

      - name: Create URL
        run: |
          repository=`echo ${GITHUB_REPOSITORY} | sed 's/.*\///g' | tr [:upper:] [:lower:]`
          branch=`echo ${GITHUB_REF} | sed 's/.*\///g' | tr [:upper:] [:lower:]`
          owner=`echo ${GITHUB_REPOSITORY} | sed 's/\/.*//g' | tr [:upper:] [:lower:]`
          URL="https://${repository}-git-${branch}-${owner}.vercel.app"
          echo "CYPRESS_baseUrl=${URL}" >> $GITHUB_ENV
          echo ${{ github.event.deployment.id }}

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install: false
          wait-on: ${{ env.CYPRESS_baseUrl }}/api/healthcheck
          wait-on-timeout: 120

      - name: Store Artifact
        uses: actions/upload-artifact@v2
        with:
          name: video
          path: cypress/videos
