name: Tests

on: [push]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Caches
        uses: actions/cache@v2
        id: yarn-build-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Node14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install
        run: yarn install

      - name: Jest
        run: yarn coverage

      - name: Store Artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage
  build:
    needs: coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Caches
        uses: actions/cache@v2
        id: yarn-build-cache
        with:
          path: |
            .next
            node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Node14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install
        run: yarn install

      - name: Build
        run: yarn build

      - name: Store Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Bundle analyzer
          path: |
            .next/analyze
            .next/server/analyze
  perf:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Caches
        uses: actions/cache@v2
        id: yarn-build-cache
        with:
          path: |
            .next
            node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Node14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install
        run: npm install && npm install -g @lhci/cli@0.7.x

      - name: Lhci
        run: lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
  e2e:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Caches
        uses: actions/cache@v2
        id: yarn-build-cache
        with:
          path: |
            .next
            node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Node14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install
        run: yarn install

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install: false
          headless: true
          start: yarn start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120

      - name: Store Artifact
        uses: actions/upload-artifact@v2
        with:
          name: video
          path: cypress/videos
